### ISSUE TITLE
Add aliases for the commands

### ISSUE THREAD

**Issue by mjpitz** [depscloud/cli#19]
Right now, we're strict about the keyword used when fetching data. We should add some aliases to help facilitate use. For example:

* `sources: [ source, srcs, src ]`
* `modules: [ module, mods, mod ]`
* `dependents: [ dependent ]`
* `dependencies: [ dependency ]`

**Comment by kendallm** [comment]
Opened https://github.com/depscloud/cli/pull/29 to address this issue.

**Comment by mjpitz** [comment]
Thanks @kendallm for your first pull request!
